# Generated by Django 3.1.2 on 2020-10-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doyaApp', '0004_auto_20201021_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news_data',
        ),
    ]
